- name: Set up of Cart server
  hosts: cart
  become: yes
  tasks: 
  - name: Disable nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: Enable Nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Install Nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create usersystem roboshop
    ansible.builtin.user: 
      name: roboshop
      comment: Roboshop System User
      system: true
      shell: /sbin/nologin
      home: /app

## It is safe to delete the file, if it exist because if any changes made will be relecting

  - name: Delete /app directory if exist
    ansible.builtin.file:
      path: /app
      state: absent

  - name: Creating app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Delete cart file if exist
    ansible.builtin.file:
      path: /tmp/cart.zip
      state: absent
  
  - name: Download cart application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip 
      dest: /tmp/cart.zip

  - name: Extract cart application
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: Install Dependencies
    community.general.npm:
      path: /app

  - name: Copy the Cart Services
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: Daemon Reload Start and Enable Cart
    ansible.builtin.systemd_service:
      name: cart
      state: started
      enabled: yes
      daemon_reload: true

  
