- name: Setup of shipping Server
  hosts: shipping
  become: yes
  tasks:
  - name: Install Maven and MySQL package
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - maven
    - mysql
    
  - name: create usersystem roboshop
    ansible.builtin.user: 
      name: roboshop
      comment: Roboshop System User
      system: true
      shell: /sbin/nologin
      home: /app
## It is safe to delete the file, if it exist because if any changes made will be relecting

  - name: Delete /app directory if exist
    ansible.builtin.file:
      path: /app
      state: absent

  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Delete shipping file if exist
    ansible.builtin.file:
      path: /tmp/shipping.zip
      state: absent

  - name: Download shipping application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip 
      dest: /tmp/shipping.zip

  - name: Extract shipping application
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: Installing Dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: Move jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 

  - name: Copy Shipping Services
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: Daemon Reload Start and Enable Catalogue
    ansible.builtin.systemd_service:
      name: catalogue
      state: started
      enabled: yes
      daemon_reload: true

  - name: Import shipping data into mysql
    community.mysql.mysql_db:
      state: import
      name: all
      login_host: mysql.galpalfan.shop
      login_user: root
      login_password: RoboShop@1
      target: "{{ item }}"
    loop: 
      - /app/db/schema.sql
      - /app/db/app-user.sql 
      - /app/db/master-data.sql

  






  
